language: elixir
cache:
  directories:
    - priv/plts
otp_release:
  - 20.3
  - 21.3
  - 22.3
elixir:
  - 1.8.2
  - 1.9.4
  - 1.10.2
matrix:
  include:
    - elixir: 1.10.2
      otp_release: 22.2
      env:
        - TEST_PERSISTENT_TERM=true
  exclude:
    - elixir: 1.10.2
      otp_release: 20.3
notifications:
  recipients:
    - vincefoley@gmail.com
    - brwcodes@gmail.com
    - ben.wilson@cargosense.com
script:
  - mix format --check-formatted
  - MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, deps.compile
  - ./test.sh
  - mkdir -p priv/plts
  - MIX_ENV=test mix dialyzer
